map_merge:
  ros__parameters:
    merging_rate: 4.0
    discovery_rate: 0.5
    estimation_rate: 0.5
    estimation_confidence: 0.0
    robot_map_topic: map
    robot_map_updates_topic: map_udpates
    robot_namespace: ""
    merged_map_topic: map
    world_frame: map
    known_init_poses: true
    # known_init_poses: false

    # Define here robots' positions in the map if known_init_poses is true
    /bot_0/map_merge/init_pose_x: 0.0
    /bot_0/map_merge/init_pose_y: 0.0
    /bot_0/map_merge/init_pose_z: 0.01
    /bot_0/map_merge/init_pose_yaw: 0.0

    /bot_1/map_merge/init_pose_x: 0.0
    /bot_1/map_merge/init_pose_y: 1.0
    /bot_1/map_merge/init_pose_z: 0.01
    /bot_1/map_merge/init_pose_yaw: 0.0
    
    /bot_2/map_merge/init_pose_x: 0.0
    /bot_2/map_merge/init_pose_y: 2.0
    /bot_2/map_merge/init_pose_z: 0.01
    /bot_2/map_merge/init_pose_yaw: 0.0
